# Generated by Django 3.2.18 on 2023-04-24 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_syed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Syed',
        ),
    ]
