# Generated by Django 4.1.2 on 2023-04-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_syed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
