version: "3.2"
services:
  backend1:
    restart: always
    build:
      context: ./Backend/
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:12345678@postgres_db:5432/rantman
    volumes:
      - ./Backend:/app/Backend
    ports:
      - 8000:8000

  backend2:
    restart: always
    build:
      context: ./Backend/
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:12345678@postgres_db:5432/rantman
    volumes:
      - ./Backend:/app/Backend
    ports:
      - 8001:8000

  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345678"
      POSTGRES_DB: rantman
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend1
      - backend2
      - frontend

volumes:
  frontend_build:
  postgres_data:
