name: publish-to-LinkedIn

on:
  push:
    branches:
      - develop

env:
  CLIENT_ID: ${{ secrets.LINKEDIN_CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.LINKEDIN_CLIENT_SECRET }}

jobs:
  post_to_linkedin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Get access token
        id: get_access_token
        run: |
          echo "Client ID: $CLIENT_ID"
          echo "Client Secret: $CLIENT_SECRET"
          response=$(curl --request POST --url 'https://www.linkedin.com/oauth/v2/accessToken' \
            --header 'Content-Type: application/x-www-form-urlencoded' \
            --data-urlencode 'grant_type=client_credentials' \
            --data-urlencode "client_id=$CLIENT_ID" \
            --data-urlencode "client_secret=$CLIENT_SECRET" \
            -w "%{http_code}\n")
            if echo "$response" | grep -qE '^2[0-9]{2}$'; then
              echo "::set-output name=access_token::$(echo $response | jq -r '.access_token')"
              echo "workss"
            else
              echo "Failed to generate access token: $response"
              exit 1
            fi
