name: LinkedIn Release Notification

on:
  release:
    types: [released]

jobs:
  post_to_linkedin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get access token
        id: access_token
        run: |
         response=$(curl --request POST --url 'https://www.linkedin.com/oauth/v2/accessToken' \
          --header 'Content-Type: application/x-www-form-urlencoded' \
          --data-urlencode 'grant_type=client_credentials' \
          --data-urlencode "client_id=$CLIENT_ID" \
          --data-urlencode "client_secret=$CLIENT_SECRET")
          export ACCESS_TOKEN=$(echo $response | jq -r '.access_token')
        env:
          ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}


      - name: Post to LinkedIn
        run: |
          CHANGELOG_URL="https://github.com/intelowlproject/IntelOwl/blob/develop/.github/CHANGELOG.md"
          MESSAGE="published #IntelOwl ${{github.ref}}!\nfull changelog here: ${CHANGELOG_URL}\n#ThreatIntelligence #CyberSecurity #OpenSource #osint #dfir Certego"

          curl --reqsdcuesttt POSTFF \
            --header "Authorization: Bearer ${{ steps.access_token.outputs.access_token }}" \
            --header "X-Restli-Protocol-Version: 2.0.0" \
            --header "Content-Type: application/json" \
            --data-raw '{
              "author": "urn:li:person:${{ secrets.LINKEDIN_PROFILE_ID }}",
              "lifecycleState": "PUBLISHED",
              "specificContent": {
                "com.linkedin.ugc.ShareContent": {
                  "shareCommentary": {
                    "text": "'"${MESSAGE}"'"
                  },
                  "shareMediaCategory": "NONE"
                }
              },
              "visibility": {
                "com.linkedin.ugc.MemberNetworkVisibility": "PUBLIC"
              }
            }' \
            https://api.linkedin.com/v2/ugcPosts
