name: publish-to-LinkedIn

on:
  push:
    branches:
      - develop

env:
  CLIENT_ID: ${{ secrets.LINKEDIN_CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.LINKEDIN_CLIENT_SECRET }}

jobs:
  post_to_linkedin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests module
        run: pip install requests

      - name: Get access token
        id: get_access_token
        run: |
          import requests
          import json

          response = requests.post('https://www.linkedin.com/oauth/v2/accessToken',
                                   headers={'Content-Type': 'application/x-www-form-urlencoded'},
                                   data={
                                     'grant_type': 'client_credentials',
                                     'client_id': '${{ secrets.LINKEDIN_CLIENT_ID }}',
                                     'client_secret': '${{ secrets.LINKEDIN_CLIENT_SECRET }}'
                                   })
          
          if response.status_code == 200:
            access_token = response.json()['access_token']
            print(f"::set-output name=access_token::{access_token}")
          else:
            print(f"Failed to generate access token: {response.content}")
            exit(1)
